chore: Update to latest flutter version

diff --git a/.github/workflows/checkout.yml b/.github/workflows/checkout.yml
--- a/.github/workflows/checkout.yml
+++ b/.github/workflows/checkout.yml
@@ -4,20 +4,25 @@ on:
   workflow_dispatch:
   push:
     branches:
+      - "main"
       - "master"
-      - "develop"
-      - "feature/**"
-      - "bugfix/**"
-      - "hotfix/**"
-      - "support/**"
+      #- "dev"
+      #- "develop"
+      #- "feature/**"
+      #- "bugfix/**"
+      #- "hotfix/**"
+      #- "support/**"
     paths:
       - "lib/**.dart"
       - "test/**.dart"
       - "example/**.dart"
+      - .github/workflows/*.yml
       - "pubspec.yaml"
   pull_request:
     branches:
+      - "main"
       - "master"
+      - "dev"
       - "develop"
       - "feature/**"
       - "bugfix/**"
@@ -27,6 +32,7 @@ on:
       - "lib/**.dart"
       - "test/**.dart"
       - "example/**.dart"
+      - .github/workflows/*.yml
       - "pubspec.yaml"
 
 jobs:
@@ -38,44 +44,106 @@ jobs:
         working-directory: ./
     container:
       image: plugfox/flutter:stable
-    timeout-minutes: 10
+    env:
+      pub-cache-name: pub
+      threshold: 50
+    timeout-minutes: 15
     steps:
       - name: 🚂 Get latest code
-        uses: actions/checkout@v3
+        id: checkout
+        uses: actions/checkout@v4
+        with:
+          sparse-checkout: |
+            .github
+            pubspec.yaml
+            lib
+            test
+            analysis_options.yaml
+            CHANGELOG.md
 
-      - name: 🚃 Cache pub modules
-        uses: actions/cache@v2
-        env:
-          cache-name: cache-octopus-package
+      - name: 📤 Restore Pub modules
+        id: cache-pub-restore
+        uses: actions/cache/restore@v4
         with:
           path: |
-            $PWD/.pub_cache/
-          key: ${{ runner.os }}-pub-${{ env.cache-name }}-${{ hashFiles('**/pubspec.yaml') }}
+            $HOME/.pub-cache
+          key: ${{ runner.os }}-${{ env.pub-cache-name }}-${{ hashFiles('**/pubspec.yaml') }}
 
-      - name: 🗄️ Export pub cache directory
-        run: export PUB_CACHE=$PWD/.pub_cache/
-
-      - name: 👷 Install Dependencies
+      - name: 🗄️ Export Pub cache directory
+        id: export-pub-cache
         timeout-minutes: 1
         run: |
-          flutter pub get
+          export PUB_CACHE=$PWD/.pub_cache/
+          export PATH="$PATH":"$HOME/.pub-cache/bin"
+          echo "${HOME}/.pub-cache/bin" >> $GITHUB_PATH
 
-      #- name: 🔎 Check format
-      #  timeout-minutes: 1
-      #  run: dart format --set-exit-if-changed -l 80 -o none lib/
+      - name: 👷 Install Dependencies
+        id: install-dependencies
+        timeout-minutes: 1
+        run: |
+          apt-get update && apt-get install -y lcov
+          flutter pub get --no-example
+
+      - name: 📥 Save Pub modules
+        id: cache-pub-save
+        uses: actions/cache/save@v4
+        with:
+          path: |
+            $HOME/.pub-cache
+          key: ${{ runner.os }}-${{ env.pub-cache-name }}-${{ hashFiles('**/pubspec.yaml') }}
+
+      - name: 🔎 Check format
+        id: check-format
+        timeout-minutes: 1
+        run: dart format --set-exit-if-changed -l 80 -o none lib/
 
       - name: 📈 Check analyzer
+        id: check-analyzer
         timeout-minutes: 1
-        run: flutter analyze --fatal-infos --fatal-warnings lib/
+        run: dart analyze --fatal-infos --fatal-warnings lib/
 
-      #- name: 🧪 Run tests
+      - name: 👀 Verify versions
+        id: verify-versions
+        timeout-minutes: 1
+        run: |
+          test -f pubspec.yaml && test -f CHANGELOG.md
+          version_pubspec=$(grep '^version:' pubspec.yaml | awk '{print $2}' | sed 's/[^[:print:]]//g')
+          test -n "$version_pubspec"
+          echo "Version from pubspec.yaml: '$version_pubspec'"
+          grep -q "# $version_pubspec" CHANGELOG.md || (echo "Version not found in CHANGELOG.md" >&2; exit 1)
+
+      - name: 🧪 Run tests
+        id: run-tests
+        timeout-minutes: 2
+        run: |
+          dart pub global run coverage:test_with_coverage -fb -o coverage -- \
+            --platform vm --compiler=kernel --coverage=coverage \
+            --reporter=github --file-reporter=json:coverage/tests.json \
+            --timeout=10m --concurrency=12 --color \
+              test/test.dart
+
+      #- name: 🔍 Check coverage
+      #  id: check-coverage
       #  timeout-minutes: 2
       #  run: |
-      #    dart run coverage:test_with_coverage -fb -o coverage -- \
-      #      --concurrency=6 --platform vm --coverage=./coverage --reporter=expanded test/ws_test.dart
+      #    mv coverage/lcov.info coverage/lcov.base.info
+      #    lcov --remove coverage/lcov.base.info '*.g.dart' -o coverage/lcov.info
+      #    lcov --list coverage/lcov.info
+      #    THRESHOLD=${{ env.threshold }}
+      #    COVERAGE=$(lcov --summary coverage/lcov.info | grep -i 'lines\|Total:' | tail -n 1 | awk '{print $2}' | sed 's/%//')
+      #    echo "Coverage is $COVERAGE%"
+      #    echo $COVERAGE | awk '{if ($1 < 50) exit 1}'
 
-      #- name: 📥 Upload coverage to Codecov
-      #  timeout-minutes: 1
-      #  uses: codecov/codecov-action@v3
+      - name: 🧹 Cleanup artifacts
+        id: cleanup-artifacts
+        if: always()
+        timeout-minutes: 2
+        run: |
+          rm -rf ~/build
+
+      #- name: ✨ Upload coverage to Codecov
+      #  id: upload-coverage
+      #  timeout-minutes: 2
+      #  uses: codecov/codecov-action@v4
       #  with:
       #    token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
